import { z } from "zod";

export const COMP_NAME = "MyComp";
export const CompositionProps = z.object({
  studio: z.object({
    title: z.string(),
    name: z.string().optional(),
    version: z.string().nullable().optional(),
    voice_id: z.string().nullable().optional(),
    voice_language: z.string().nullable().optional(),
    voice_provider: z.string().nullable().optional(),
    result_path: z.string().nullable().optional(),
  }),
  scenes: z.array(
    z.object({
      index: z.number(),
      background_color: z.string().optional(),
      asset_background: z.any().nullable().optional(),
      avatars: z.array(z.any()),
      elements: z.array(z.any()),
      hotspots: z.array(z.any()),
      background_music: z.any().nullable(),
      rich_script: z.string(),
      script: z.string(),
      audio_url: z.string().optional(),
      has_faqs: z.boolean().optional(),
      id: z.number().optional(),
      metadata: z.any(),
    }),
  ),
  selectedSceneIndex: z.number(),
  selectedScenes: z.array(z.number()),
  id: z.number().optional(),
});

export const defaultMyCompProps: z.infer<typeof CompositionProps> = {
  studio: {
    title: "cta isaac",
    voice_id: "21m00Tcm4TlvDq8ikWAM",
    voice_language: "en",
    voice_provider: "elevenlabs",
    version: "1.0",
    result_path:
      "https://s3.us-west-1.amazonaws.com/acolyte-dev-studio-videos/58/videos/535/remotion/render_remotion_535_2357.mp4",
  },
  scenes: [
    {
      id: 5732,
      avatars: [],
      elements: [],
      hotspots: [],
      background_music: null,
      asset_background: null,
      survey: null,
      single_questions: [],
      videos_scene_chapter: {
        id: 3223,
        title: "Chapter 1",
        order: 0,
        is_delete_in: false,
        is_created: false,
        created_at: "2025-07-10T18:08:02.590717Z",
        updated_at: "2025-07-10T18:08:02.590735Z",
        video: 535,
        videos_version: 2357,
      },
      order_chapter: 0,
      script: "",
      rich_script: "",
      background_color: "rgba(255,255,255,1)",
      created_at: "2025-07-10T18:08:02.423169Z",
      updated_at: "2025-07-10T18:08:02.547142Z",
      index: 0,
      has_faqs: true,
      has_tokens: false,
      metadata: null,
      source: null,
      videos_version: 2357,
      selectedElements: [],
      chapterId: 3223,
      videos_scene_chapter_id: 3223,
    },
    {
      id: 5733,
      avatars: [],
      elements: [],
      hotspots: [],
      background_music: null,
      asset_background: {
        id: 170,
        uploaded_by: "Saul Rubalcava",
        topics: [],
        full_name: "Saul Rubalcava",
        name: "Jar with different scattered pills on grey background",
        asset_type: "images",
        mime_type: "image/jpeg",
        thumbnail_path: null,
        result_path:
          "https://st5.depositphotos.com/10614052/69035/i/450/depositphotos_690350178-stock-photo-jar-different-scattered-pills-grey.jpg?forcejpeg=true?v=1752171964",
        asset_uuid: "cf7cf6ee796740288eaefbaa9b29786b",
        created_at: "2025-07-10T18:08:02.758268Z",
        updated_at: "2025-07-10T18:08:02.758285Z",
        miliseconds: null,
        time: null,
        status: "uploading",
        url: "",
        is_action_button: false,
        is_library_asset: false,
        use_video_in_url: false,
        width: 6720,
        height: 4480,
        is_deposit_photo: true,
        is_background_music: false,
        deposit_photo_id: null,
        video_id: 535,
        created_by: 58,
      },
      survey: null,
      single_questions: [],
      videos_scene_chapter: {
        id: 3223,
        title: "Chapter 1",
        order: 0,
        is_delete_in: false,
        is_created: false,
        created_at: "2025-07-10T18:08:02.590717Z",
        updated_at: "2025-07-10T18:08:02.590735Z",
        video: 535,
        videos_version: 2357,
      },
      order_chapter: 0,
      script: "hola",
      rich_script: "<p>hola</p>",
      background_color: "rgba(255,255,255,1)",
      created_at: "2025-07-10T18:08:02.835519Z",
      updated_at: "2025-07-10T18:08:03.019553Z",
      index: 1,
      has_faqs: false,
      has_tokens: false,
      metadata: null,
      source: null,
      videos_version: 2357,
      selectedElements: [],
      chapterId: 3223,
      videos_scene_chapter_id: 3223,
    },
    {
      id: 5734,
      avatars: [],
      elements: [
        {
          name: "Email to",
          id: 3008,
          element_type: "button",
          asset: null,
          asset_path: null,
          metadata: {
            id: 3008,
            fill: "#C6658C",
            text: "Email to",
            align: "center",
            color: "white",
            zIndex: 1,
            fontSize: 12,
            position: {
              x: 308.00120501883794,
              y: 53.70514491179817,
              width: 100,
              height: 33,
              rotation: 0,
            },
            fontFamily: "Arial",
            fontWeight: "normal",
          },
          action: {
            id: 104,
            action: "email",
            action_type: "email",
            url: null,
            email: "ilerma@lumston.com",
            download_path: null,
            element: 3008,
            asset_id: null,
          },
        },
      ],
      hotspots: [],
      background_music: null,
      asset_background: null,
      // survey: null,
      single_questions: [],
      videos_scene_chapter: {
        id: 3223,
        title: "Chapter 1",
        order: 0,
        is_delete_in: false,
        is_created: false,
        created_at: "2025-07-10T18:08:02.590717Z",
        updated_at: "2025-07-10T18:08:02.590735Z",
        video: 535,
        videos_version: 2357,
      },
      order_chapter: 0,
      script: "",
      rich_script: "",
      background_color: "rgba(255,255,255,1)",
      created_at: "2025-07-10T18:08:03.094224Z",
      updated_at: "2025-07-10T18:08:03.230601Z",
      index: 2,
      has_faqs: false,
      has_tokens: false,
      metadata: null,
      source: null,
      videos_version: 2357,
      selectedElements: [],
      chapterId: 3223,
      videos_scene_chapter_id: 3223,
    },
  ],
  selectedSceneIndex: 0,
  selectedScenes: [],
};

export const DURATION_IN_FRAMES = 200;
export const VIDEO_WIDTH = 720;
export const VIDEO_HEIGHT = 400;
export const VIDEO_FPS = 30;
